name: CI

on:
  push

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the Repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install dependencies
      - name: Install
        run: npm ci
      
      # Run tests
      - name: Test
        run: npm run test
        
      # Create build
      - name: Build
        run: npm run build
        
      # Check git status
      - name: Determine Status
        run: |
          if git status | grep -q 'nothing to commit'; then
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          else
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          fi
      
      # Commit if build is different
      - name: Commit Build
        if: ${{ env.HAS_CHANGES == true }}
        run: |
          git config --local user.email "ciworkflow@github.fake"
          git config --local user.name "CI Workflow"
          git add dist
          git commit -m "Build updated"
