name: 'Push Tag'

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  bump_and_tag:
    name: Bump and Tag
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          persist-credentials: true
          ref: ${{ github.ref }}
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: 'Bump version and create tag'
        id: version-bump
        uses: 'shipt/bump-and-tag@main'
        with:
          wording-major: 'MAJOR'
          wording-minor: 'feat'
          wording-patch: 'patch,fix,bug'
